[498.2099] # WidowMine - WIDOWMINEATTACK_WIDOWMINEATTACK
disallow = true

[150.1] # InfestedTerransEgg - SMART
disallow = true

[150.18] # InfestedTerransEgg - HOLDPOSITION_HOLD
disallow = true

[150.17] # InfestedTerransEgg - PATROL_PATROL
disallow = true

[150.16] # InfestedTerransEgg - MOVE_MOVE
disallow = true
